=== yoyosource/BOTC-FoF/character_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "Script Character",
  "required": [
    "id",
    "name",
    "team",
    "ability"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "title": "Character ID, alphanumeric lowercase",
      "maxLength": 50,
      "examples": [
        "washerwoman",
        "lilmonsta",
        "fanggu"
      ]
    },
    "name": {
      "type": "string",
      "title": "Character name",
      "maxLength": 30,
      "examples": [
        "Washer Woman",
        "Lil' Monsta",
        "Fang-Gu"
      ]
    },
    "image": {
      "oneOf": [
        {
          "type": "string",
          "format": "uri",
          "title": "Character icon",
          "examples": [
            "https://i.imgur.com/character-icon.png"
          ]
        },
        {
          "type": "array",
          "title": "Set of character icon URLs",
          "description": "For non-traveller characters, the icons should be regular alignment and flipped alignment, for travellers they should be unaligned, good alignment and evil alignment",
          "minItems": 1,
          "maxItems": 3,
          "items": {
            "type": "string",
            "format": "uri"
          },
          "examples": [
            [
              "https://imgur.com/townsfolk.png",
              "https://imgur.com/townsfolk_evil.png"
            ],
            [
              "https://imgur.com/minion.png",
              "https://imgur.com/minion_good.png"
            ],
            [
              "https://imgur.com/traveller.png",
              "https://imgur.com/traveller_good.png",
              "https://imgur.com/traveller_evil.png"
            ]
          ]
        }
      ]
    },
    "team": {
      "type": "string",
      "title": "Character team",
      "enum": [
        "townsfolk",
        "outsider",
        "minion",
        "demon",
        "traveller",
        "fabled"
      ]
    },
    "edition": {
      "type": "string",
      "title": "The edition ID",
      "maxLength": 50,
      "examples": [
        "tb",
        "bmr",
        "snv",
        "fallofrome"
      ]
    },
    "ability": {
      "type": "string",
      "title": "Character ability",
      "maxLength": 250,
      "examples": [
        "You start knowing that 1 of 2 players is a particular Townsfolk.",
        "Each night, Minions choose who babysits Lil' Monsta's token \u0026 \"is the Demon\". A player dies each night*. [+1 Minion]",
        "Each night*, choose a player: they die. The 1st Outsider this kills becomes an evil Fang Gu \u0026 you die instead. [+1 Outsider]"
      ]
    },
    "flavor": {
      "type": "string",
      "title": "Character flavor text",
      "maxLength": 500,
      "examples": [
        "Bloodstains on a dinner jacket? No, this is cooking sherry. How careless.",
        "Certainly madam, under normal circumstances, you may borrow the Codex Malificarium from the library vaults. However, you do not seem to be a member.",
        "It is a fine night for a stroll, wouldn't you say, Mister Morozov? Or should I say... BARON Morozov?"
      ]
    },
    "firstNight": {
      "type": "number",
      "title": "First night wake-up priority. 0 means this character doesn't wake during the first night.",
      "examples": [
        37,
        0,
        15
      ]
    },
    "firstNightReminder": {
      "type": "string",
      "title": "First night Storyteller reminder",
      "maxLength": 500,
      "examples": [
        "Show the Townsfolk character token. Point to both the *TOWNSFOLK* and *WRONG* players.",
        "Wake all Minions, allow them to choose a babysitter :reminder:",
        ""
      ]
    },
    "otherNight": {
      "type": "number",
      "title": "Other nights wake-up priority. 0 means this character doesn't wake during other nights.",
      "examples": [
        0,
        10,
        15
      ]
    },
    "otherNightReminder": {
      "type": "string",
      "title": "Other nights Storyteller reminder",
      "maxLength": 500,
      "examples": [
        "",
        "Wake all Minions, allow them to choose a babysitter :reminder: A player might die :reminder:",
        "The Fang Gu chooses a player. :reminder: If they chose an Outsider (once only): Replace the Outsider token with the spare Fang Gu token. Put the Fang Gu to sleep. Wake the target. Show the *YOU ARE* and Fang Gu tokens \u0026 give a thumbs-down. :reminder:"
      ]
    },
    "reminders": {
      "type": "array",
      "maxItems": 20,
      "default": [],
      "title": "Character reminder tokens",
      "items": {
        "type": "string",
        "maxLength": 30,
        "examples": [
          "Townsfolk",
          "Wrong",
          "Dead",
          "Is The Demon"
        ]
      }
    },
    "remindersGlobal": {
      "type": "array",
      "maxItems": 20,
      "default": [],
      "title": "Global character reminder tokens, which will be selectable even when the character is not in play.",
      "items": {
        "type": "string",
        "maxLength": 25,
        "examples": [
          "Drunk",
          "Is The Philosopher"
        ]
      }
    },
    "setup": {
      "type": "boolean",
      "title": "Whether this character has a ability that is relevant for the game setup.",
      "default": false
    },
    "jinxes": {
      "type": "array",
      "title": "Jinxes with other characters on this script",
      "items": {
        "type": "object",
        "title": "An individual Jinx pair",
        "required": [
          "id",
          "reason"
        ],
        "properties": {
          "id": {
            "type": "string",
            "title": "The ID of the other character this one is jinxed with.",
            "maxLength": 50,
            "examples": [
              "spy",
              "fanggu",
              "lilmonsta"
            ]
          },
          "reason": {
            "type": "string",
            "title": "The Jinx explanation",
            "maxLength": 500,
            "examples": [
              "If the Cannibal gains the Butler ability, the Cannibal learns this.",
              "The Mathematician learns if the Lunatic attacks a different player(s) than the real Demon attacked."
            ]
          }
        }
      }
    },
    "special": {
      "type": "array",
      "title": "Special app integration features for this character",
      "items": {
        "type": "object",
        "title": "A special app integration feature",
        "required": [
          "name",
          "type"
        ],
        "properties": {
          "type": {
            "type": "string",
            "title": "The integration type, where the feature will be used.",
            "description": "Currently supported values are:\n selection - during character selection,\n signal - during night signaling,\n ability - when clicking on the character token,\n vote - during a vote,\n reveal - at the end of the game, before characters are revealed,\n player - an ability that can be initiated by the player",
            "enum": [
              "selection",
              "ability",
              "signal",
              "vote",
              "reveal",
              "player"
            ]
          },
          "name": {
            "type": "string",
            "title": "The feature name reference",
            "description": "This is a list of the currently implemented special features and will be growing over time.",
            "enum": [
              "grimoire",
              "pointing",
              "ghost-votes",
              "distribute-roles",
              "bag-disabled",
              "bag-duplicate",
              "multiplier",
              "hidden",
              "replace-character",
              "player",
              "card",
              "open-eyes"
            ]
          },
          "value": {
            "oneOf": [
              {
                "type": "string",
                "title": "Special ability text value",
                "maxLength": 50,
                "description": "The text value that will be used by the special ability."
              },
              {
                "type": "number",
                "title": "Special ability number value",
                "description": "The numeric value that will be used by the special ability."
              }
            ]
          },
          "time": {
            "type": "string",
            "title": "At which point during the game can the ability be used",
            "enum": [
              "pregame",
              "day",
              "night",
              "firstNight",
              "firstDay",
              "otherNight",
              "otherDay"
            ]
          },
          "global": {
            "type": "string",
            "title": "Global ability scope",
            "description": "If it's a global ability that can be used without the character being in play, this property defines on which characters it can be used. This does not work on Fabled, because they are not considered to be on the Script.",
            "enum": [
              "townsfolk",
              "outsider",
              "minion",
              "demon",
              "traveller",
              "dead"
            ]
          }
        },
        "examples": [
          {
            "type": "player",
            "name": "open-eyes",
            "time": "night"
          },
          {
            "type": "signal",
            "name": "card",
            "value": "This is a Custom ST Card"
          },
          {
            "type": "ability",
            "name": "pointing",
            "time": "night",
            "global": "minion"
          },
          {
            "type": "vote",
            "name": "multiplier",
            "value": "3"
          }
        ]
      }
    }
  },
  "examples": [
    {
      "id": "washerwoman",
      "name": "Washerwoman",
      "edition": "tb",
      "team": "townsfolk",
      "firstNightReminder": "Show the Townsfolk character token. Point to both the *TOWNSFOLK* and *WRONG* players.",
      "otherNightReminder": "",
      "reminders": [
        "Townsfolk",
        "Wrong"
      ],
      "setup": false,
      "ability": "You start knowing that 1 of 2 players is a particular Townsfolk.",
      "flavor": "Bloodstains on a dinner jacket? No, this is cooking sherry. How careless.",
      "firstNight": 37,
      "otherNight": 0
    }
  ]
}

=== yoyosource/BOTC-FoF/Townsfolk/Merchant/Merchant.json
{
  "id": "merchant",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Merchant/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Merchant/image_evil.png?raw=true"
  ],
  "name": "Merchant",
  "team": "townsfolk",
  "otherNightReminder": "Wake up the Merchant and have them choose 1 or 2. They may only choose 2 if they are, to their knowledge, holding a potion. If they choose 1, put a potion on them. If they choose 2, have them name a potion they think they hold and another, alive player. If they hold that potion, move it to the chosen player.",
  "ability": "Each night*, choose either 1) receive a potion, or if you hold a potion 2) choose a potion you think you are holding and a player (not yourself) to receive that potion.",
  "flavor": "I will buy with you, sell with you, talk with you, walk with you, and so following, but I will not eat with you, drink with you, nor pray with you."
}

=== yoyosource/BOTC-FoF/Townsfolk/Auctioneer/Auctioneer.json
{
  "id": "auctioneer",
  "edition": "custom",
  "reminders": [
    "Market Day (Tomorrow)",
    "Market Day (Today)"
  ],
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Auctioneer/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Auctioneer/image_evil.png?raw=true"
  ],
  "name": "Auctioneer",
  "team": "townsfolk",
  "otherNightReminder": "If today was a Market Day wake up the Auctioneer and signal them how many evil players traded tonight.",
  "ability": "Once per game, during the day publicly declare tomorrow to be Market Day. The night after a Market Day learn how many evil players traded.",
  "flavor": "Aaaaaaaand, sold to the robed stranger with the pitchfork!"
}

=== yoyosource/BOTC-FoF/Fabled/TheCauldron/TheCauldron.json
{
  "id": "thecauldron",
  "edition": "custom",
  "reminders": [
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Eyed the Cauldron",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions",
    "Flipped Potions"
  ],
  "name": "The Cauldron",
  "team": "fabled",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Fabled/TheCauldron/image.png?raw=true"
  ],
  "ability": " ",
  "flavor": "The Pot might be calling the Kettle black, but everyone agrees that the Cauldron is green."
}

=== yoyosource/BOTC-FoF/Demon/Clofou/Clofou.json
{
  "id": "clofou",
  "edition": "custom",
  "reminders": [
    "Dead",
    "Turn Evil"
  ],
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Demon/Clofou/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Demon/Clofou/image_good.png?raw=true"
  ],
  "name": "Clofou",
  "team": "demon",
  "otherNightReminder": "Wake up the Clofou and have them choose a player. Then put them back to sleep and put the Clofou's *Dead* reminder token on the chosen player. The first time they are neighbouring an alive Outsider wake them and tell them that they are evil.",
  "setup": true,
  "ability": "Each night*, choose a player; they die. The first time you neighbour or trade with a living Outsider, they become evil. [+1 Outsider]",
  "flavor": "The saints were his friends, and blessed him; the monsters were his friends, and guarded him."
}

=== yoyosource/BOTC-FoF/Minion/Crone/Crone.json
{
  "id": "crone",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Minion/Crone/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Minion/Crone/image_good.png?raw=true"
  ],
  "name": "Crone",
  "team": "minion",
  "reminders": [
    "Trading, Evil",
    "Trading, Good"
  ],
  "otherNightReminder": "If the Crone traded with an evil player tonight, swap the character tokens of those players on the Grimoire, then wake them up and show them their new tokens. If they traded with a good player tonight, wake them up and show them that player’s token.",
  "ability": "Each night if you traded with an evil player you swap characters. If you traded with a good player you learn their character.",
  "flavor": "Why, dearie! You ain't afraid of little old me, are you? Not when there are so much worse things, lurking in the dark?"
}

=== yoyosource/BOTC-FoF/Townsfolk/Scout/Scout.json
{
  "id": "scout",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Scout/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Scout/image_evil.png?raw=true"
  ],
  "setup": true,
  "name": "Scout",
  "team": "townsfolk",
  "firstNightReminder": "Wake the Scout and signal a number equal to the highest number of Townsfolk players sitting in a line.",
  "ability": "You start knowing the longest chain of Townfolk players. [+0/+1 Outsiders]",
  "special": [
    {
      "type": "signal",
      "name": "card",
      "value": "The longest chain of townsfolk players is:",
      "time": "firstNight"
    }
  ]
}

=== yoyosource/BOTC-FoF/Fabled/Solicitor/Solicitor.json
{
  "id": "solicitor",
  "edition": "custom",
  "otherNightReminder": "Remove any *No Ability* Reminder token. Put the *No Ability* Reminder on any Townsfolk with any *Trade* Reminder token on them.",
  "reminders": [
    "Trade 1",
    "Trade 1",
    "Trade 2",
    "Trade 2",
    "Trade 3",
    "Trade 3",
    "Trade 4",
    "Trade 4",
    "Trade 5",
    "Trade 5",
    "Trade 6",
    "Trade 6"
  ],
  "name": "Solicitor",
  "team": "fabled",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Fabled/Solicitor/image.png?raw=true"
  ],
  "ability": "2 living players may publicly choose to trade all potions once per day. If either player is dead when the trade would happen, no trade occurs.",
  "flavor": "Oh, I love the Festival! It's my busiest workday of the year!"
}

=== yoyosource/BOTC-FoF/Outsider/Student/Student.json
{
  "id": "student",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Outsider/Student/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Outsider/Student/image_evil.png?raw=true"
  ],
  "name": "Student",
  "team": "outsider",
  "ability": "You may only vote or nominate if you have a trade active.",
  "flavor": "Education is not the filling of a pail, but the lighting of a fire."
}
