=== yoyosource/BOTC-FoF/character_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "Script Character",
  "required": [
    "id",
    "name",
    "team",
    "ability"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "title": "Character ID, alphanumeric lowercase",
      "maxLength": 50,
      "examples": [
        "washerwoman",
        "lilmonsta",
        "fanggu"
      ]
    },
    "name": {
      "type": "string",
      "title": "Character name",
      "maxLength": 30,
      "examples": [
        "Washer Woman",
        "Lil' Monsta",
        "Fang-Gu"
      ]
    },
    "image": {
      "oneOf": [
        {
          "type": "string",
          "format": "uri",
          "title": "Character icon",
          "examples": [
            "https://i.imgur.com/character-icon.png"
          ]
        },
        {
          "type": "array",
          "title": "Set of character icon URLs",
          "description": "For non-traveller characters, the icons should be regular alignment and flipped alignment, for travellers they should be unaligned, good alignment and evil alignment",
          "minItems": 1,
          "maxItems": 3,
          "items": {
            "type": "string",
            "format": "uri"
          },
          "examples": [
            [
              "https://imgur.com/townsfolk.png",
              "https://imgur.com/townsfolk_evil.png"
            ],
            [
              "https://imgur.com/minion.png",
              "https://imgur.com/minion_good.png"
            ],
            [
              "https://imgur.com/traveller.png",
              "https://imgur.com/traveller_good.png",
              "https://imgur.com/traveller_evil.png"
            ]
          ]
        }
      ]
    },
    "team": {
      "type": "string",
      "title": "Character team",
      "enum": [
        "townsfolk",
        "outsider",
        "minion",
        "demon",
        "traveller",
        "fabled"
      ]
    },
    "edition": {
      "type": "string",
      "title": "The edition ID",
      "maxLength": 50,
      "examples": [
        "tb",
        "bmr",
        "snv",
        "fallofrome"
      ]
    },
    "ability": {
      "type": "string",
      "title": "Character ability",
      "maxLength": 250,
      "examples": [
        "You start knowing that 1 of 2 players is a particular Townsfolk.",
        "Each night, Minions choose who babysits Lil' Monsta's token \u0026 \"is the Demon\". A player dies each night*. [+1 Minion]",
        "Each night*, choose a player: they die. The 1st Outsider this kills becomes an evil Fang Gu \u0026 you die instead. [+1 Outsider]"
      ]
    },
    "flavor": {
      "type": "string",
      "title": "Character flavor text",
      "maxLength": 500,
      "examples": [
        "Bloodstains on a dinner jacket? No, this is cooking sherry. How careless.",
        "Certainly madam, under normal circumstances, you may borrow the Codex Malificarium from the library vaults. However, you do not seem to be a member.",
        "It is a fine night for a stroll, wouldn't you say, Mister Morozov? Or should I say... BARON Morozov?"
      ]
    },
    "firstNight": {
      "type": "number",
      "title": "First night wake-up priority. 0 means this character doesn't wake during the first night.",
      "examples": [
        37,
        0,
        15
      ]
    },
    "firstNightReminder": {
      "type": "string",
      "title": "First night Storyteller reminder",
      "maxLength": 500,
      "examples": [
        "Show the Townsfolk character token. Point to both the *TOWNSFOLK* and *WRONG* players.",
        "Wake all Minions, allow them to choose a babysitter :reminder:",
        ""
      ]
    },
    "otherNight": {
      "type": "number",
      "title": "Other nights wake-up priority. 0 means this character doesn't wake during other nights.",
      "examples": [
        0,
        10,
        15
      ]
    },
    "otherNightReminder": {
      "type": "string",
      "title": "Other nights Storyteller reminder",
      "maxLength": 500,
      "examples": [
        "",
        "Wake all Minions, allow them to choose a babysitter :reminder: A player might die :reminder:",
        "The Fang Gu chooses a player. :reminder: If they chose an Outsider (once only): Replace the Outsider token with the spare Fang Gu token. Put the Fang Gu to sleep. Wake the target. Show the *YOU ARE* and Fang Gu tokens \u0026 give a thumbs-down. :reminder:"
      ]
    },
    "reminders": {
      "type": "array",
      "maxItems": 20,
      "default": [],
      "title": "Character reminder tokens",
      "items": {
        "type": "string",
        "maxLength": 30,
        "examples": [
          "Townsfolk",
          "Wrong",
          "Dead",
          "Is The Demon"
        ]
      }
    },
    "remindersGlobal": {
      "type": "array",
      "maxItems": 20,
      "default": [],
      "title": "Global character reminder tokens, which will be selectable even when the character is not in play.",
      "items": {
        "type": "string",
        "maxLength": 25,
        "examples": [
          "Drunk",
          "Is The Philosopher"
        ]
      }
    },
    "setup": {
      "type": "boolean",
      "title": "Whether this character has a ability that is relevant for the game setup.",
      "default": false
    },
    "jinxes": {
      "type": "array",
      "title": "Jinxes with other characters on this script",
      "items": {
        "type": "object",
        "title": "An individual Jinx pair",
        "required": [
          "id",
          "reason"
        ],
        "properties": {
          "id": {
            "type": "string",
            "title": "The ID of the other character this one is jinxed with.",
            "maxLength": 50,
            "examples": [
              "spy",
              "fanggu",
              "lilmonsta"
            ]
          },
          "reason": {
            "type": "string",
            "title": "The Jinx explanation",
            "maxLength": 500,
            "examples": [
              "If the Cannibal gains the Butler ability, the Cannibal learns this.",
              "The Mathematician learns if the Lunatic attacks a different player(s) than the real Demon attacked."
            ]
          }
        }
      }
    },
    "special": {
      "type": "array",
      "title": "Special app integration features for this character",
      "items": {
        "type": "object",
        "title": "A special app integration feature",
        "required": [
          "name",
          "type"
        ],
        "properties": {
          "type": {
            "type": "string",
            "title": "The integration type, where the feature will be used.",
            "description": "Currently supported values are:\n selection - during character selection,\n signal - during night signaling,\n ability - when clicking on the character token,\n vote - during a vote,\n reveal - at the end of the game, before characters are revealed,\n player - an ability that can be initiated by the player",
            "enum": [
              "selection",
              "ability",
              "signal",
              "vote",
              "reveal",
              "player"
            ]
          },
          "name": {
            "type": "string",
            "title": "The feature name reference",
            "description": "This is a list of the currently implemented special features and will be growing over time.",
            "enum": [
              "grimoire",
              "pointing",
              "ghost-votes",
              "distribute-roles",
              "bag-disabled",
              "bag-duplicate",
              "multiplier",
              "hidden",
              "replace-character",
              "player",
              "card",
              "open-eyes"
            ]
          },
          "value": {
            "oneOf": [
              {
                "type": "string",
                "title": "Special ability text value",
                "maxLength": 50,
                "description": "The text value that will be used by the special ability."
              },
              {
                "type": "number",
                "title": "Special ability number value",
                "description": "The numeric value that will be used by the special ability."
              }
            ]
          },
          "time": {
            "type": "string",
            "title": "At which point during the game can the ability be used",
            "enum": [
              "pregame",
              "day",
              "night",
              "firstNight",
              "firstDay",
              "otherNight",
              "otherDay"
            ]
          },
          "global": {
            "type": "string",
            "title": "Global ability scope",
            "description": "If it's a global ability that can be used without the character being in play, this property defines on which characters it can be used. This does not work on Fabled, because they are not considered to be on the Script.",
            "enum": [
              "townsfolk",
              "outsider",
              "minion",
              "demon",
              "traveller",
              "dead"
            ]
          }
        },
        "examples": [
          {
            "type": "player",
            "name": "open-eyes",
            "time": "night"
          },
          {
            "type": "signal",
            "name": "card",
            "value": "This is a Custom ST Card"
          },
          {
            "type": "ability",
            "name": "pointing",
            "time": "night",
            "global": "minion"
          },
          {
            "type": "vote",
            "name": "multiplier",
            "value": "3"
          }
        ]
      }
    }
  },
  "examples": [
    {
      "id": "washerwoman",
      "name": "Washerwoman",
      "edition": "tb",
      "team": "townsfolk",
      "firstNightReminder": "Show the Townsfolk character token. Point to both the *TOWNSFOLK* and *WRONG* players.",
      "otherNightReminder": "",
      "reminders": [
        "Townsfolk",
        "Wrong"
      ],
      "setup": false,
      "ability": "You start knowing that 1 of 2 players is a particular Townsfolk.",
      "flavor": "Bloodstains on a dinner jacket? No, this is cooking sherry. How careless.",
      "firstNight": 37,
      "otherNight": 0
    }
  ]
}

=== yoyosource/BOTC-FoF/Minion/Chemist/Chemist.json
{
  "id": "chemist",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Minion/Chemist/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Minion/Chemist/image_good.png?raw=true"
  ],
  "name": "Chemist",
  "team": "minion",
  "firstNightReminder": "Wake up the Chemist and show them the *Cauldron*. Have them choose either 1 or 2. If they choose 1, have them choose 2 potions in the Cauldron and then swap those potion's places. If they choose 2, have them choose a good potion held by another player; move it to them and replace it with an Empty Potion.",
  "otherNightReminder": "Wake up the Chemist and show them the *Cauldron*. Have them choose either 1 or 2. If they choose 1, have them choose 2 potions in the Cauldron and then swap those potion's places. If they choose 2, have them choose a good potion held by another player; move it to them and replace it with an Empty Potion.",
  "ability": "Each night, eye the cauldron; either choose 1) 2 potions to swap places, or 2) a good potion another player holds; you receive it, theirs is emptied.",
  "flavor": "Life is just chemicals. A drop here, a drip there, everything's changed."
}

=== yoyosource/BOTC-FoF/Townsfolk/Clerk/Clerk.json
{
  "id": "clerk",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Clerk/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Clerk/image_evil.png?raw=true"
  ],
  "name": "Clerk",
  "team": "townsfolk",
  "firstNightReminder":"Wake up the Clerk and either show them a potion of a type that an evil player has received tonight, or if none has been received by an evil player tonight, signal a no.",
  "otherNightReminder": "Wake up the Clerk and either show them a potion of a type that an evil player has received tonight, or if none has been received by an evil player tonight, signal a no.",
  "ability": "Each night*, you learn a type of potion that an evil player (not a traveller) has received tonight, or if none has been received.",
  "flavor": "Employers are like horses — they require management.",
  "special": [
    {
      "type": "signal",
      "name": "card",
      "value": "An evil player received this potion",
      "time": "otherNight"
    }
  ]
}

=== yoyosource/BOTC-FoF/Townsfolk/PigeonFancier/PigeonFancier.json
{
  "id": "pigeonfancier",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/PigeonFancier/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/PigeonFancier/image_evil.png?raw=true"
  ],
  "name": "Pigeon Fancier",
  "team": "townsfolk",
  "ability": "While dead, if you died at night, the Glassblower only gives out good potions. [+Glassblower]"
}

=== yoyosource/BOTC-FoF/Townsfolk/Druid/Druid.json
{
  "id": "druid",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Druid/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Druid/image_evil.png?raw=true"
  ],
  "name": "Druid",
  "team": "townsfolk",
  "ability": "Each night* you may choose a dead player; learn their character type and you might receive an evil potion.",
  "flavor": "The great use of life is to spend it for something that will outlast it.",
  "special": [
    {
      "type": "signal",
      "name": "card",
      "value": "Select a dead player.",
      "time": "otherNight"
    }
  ]
}

=== yoyosource/BOTC-FoF/Townsfolk/Apothecary/Apothecary.json
{
  "id": "apothecary",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Apothecary/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Apothecary/image_evil.png?raw=true"
  ],
  "name": "Apothecary",
  "team": "townsfolk",
  "ability": "All types of potions you are holding are nullified.",
  "flavor": "Medicine is not only a science; it is also an art. It does not consist of compounding pills and plasters; it deals with the very processes of life, which must be understood before they may be guided."
}

=== yoyosource/BOTC-FoF/Townsfolk/Farrier/Farrier.json
{
  "id": "farrier",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Farrier/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Farrier/image_evil.png?raw=true"
  ],
  "name": "Farrier",
  "team": "townsfolk",
  "firstNightReminder": "Wake up the Farrier and have them choose another player. Then signal them either yes or no, dependent on if that player is seated closer to an evil player other than themselves, than the Farrier is seated to an evil player.",
  "otherNightReminder": "Wake up the Farrier and have them choose another player that they have not chosen previously. Then signal them either yes or no, dependent on if that player is seated closer to an evil player other than themselves, than the Farrier is seated to an evil player.",
  "ability": "Each night, choose a new player (not yourself); you learn if they are closer to an evil player (not themselves) than you are.",
  "flavor": "Well, that is close. But close only counts for hand grenades.",
  "special": [
    {
      "type": "signal",
      "name": "card",
      "value": "You are closer to an evil player.",
      "time": "night"
    },
    {
      "type": "signal",
      "name": "card",
      "value": "They are closer to an evil player.",
      "time": "night"
    }
  ]
}

=== yoyosource/BOTC-FoF/Townsfolk/Botanist/Botanist.json
{
  "id": "botanist",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Botanist/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Botanist/image_evil.png?raw=true"
  ],
  "reminders": [
    "In Play"
  ],
  "name": "Botanist",
  "team": "townsfolk",
  "ability": "You start knowing 2 good characters; 1 is in play and 1 is a demon bluff.",
  "special": [
    {
      "type": "signal",
      "name": "card",
      "value": "Your characters",
      "time": "firstNight"
    }
  ]
}

=== yoyosource/BOTC-FoF/Townsfolk/Baptist/Baptist.json
{
  "id": "baptist",
  "edition": "custom",
  "reminders": [
    "Cannot die"
  ],
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Baptist/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Baptist/image_evil.png?raw=true"
  ],
  "name": "Baptist",
  "team": "townsfolk",
  "ability": "Each night*, choose 2 living players (not yourself); either player might receive a potion. If either received an evil potion you cannot die tonight.",
  "flavor": "It's never too soon to contemplate eternal damnation, sir!"
}
