=== yoyosource/BOTC-FoF/character_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "title": "Script Character",
  "required": [
    "id",
    "name",
    "team",
    "ability"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "title": "Character ID, alphanumeric lowercase",
      "maxLength": 50,
      "examples": [
        "washerwoman",
        "lilmonsta",
        "fanggu"
      ]
    },
    "name": {
      "type": "string",
      "title": "Character name",
      "maxLength": 30,
      "examples": [
        "Washer Woman",
        "Lil' Monsta",
        "Fang-Gu"
      ]
    },
    "image": {
      "oneOf": [
        {
          "type": "string",
          "format": "uri",
          "title": "Character icon",
          "examples": [
            "https://i.imgur.com/character-icon.png"
          ]
        },
        {
          "type": "array",
          "title": "Set of character icon URLs",
          "description": "For non-traveller characters, the icons should be regular alignment and flipped alignment, for travellers they should be unaligned, good alignment and evil alignment",
          "minItems": 1,
          "maxItems": 3,
          "items": {
            "type": "string",
            "format": "uri"
          },
          "examples": [
            [
              "https://imgur.com/townsfolk.png",
              "https://imgur.com/townsfolk_evil.png"
            ],
            [
              "https://imgur.com/minion.png",
              "https://imgur.com/minion_good.png"
            ],
            [
              "https://imgur.com/traveller.png",
              "https://imgur.com/traveller_good.png",
              "https://imgur.com/traveller_evil.png"
            ]
          ]
        }
      ]
    },
    "team": {
      "type": "string",
      "title": "Character team",
      "enum": [
        "townsfolk",
        "outsider",
        "minion",
        "demon",
        "traveller",
        "fabled"
      ]
    },
    "edition": {
      "type": "string",
      "title": "The edition ID",
      "maxLength": 50,
      "examples": [
        "tb",
        "bmr",
        "snv",
        "fallofrome"
      ]
    },
    "ability": {
      "type": "string",
      "title": "Character ability",
      "maxLength": 250,
      "examples": [
        "You start knowing that 1 of 2 players is a particular Townsfolk.",
        "Each night, Minions choose who babysits Lil' Monsta's token \u0026 \"is the Demon\". A player dies each night*. [+1 Minion]",
        "Each night*, choose a player: they die. The 1st Outsider this kills becomes an evil Fang Gu \u0026 you die instead. [+1 Outsider]"
      ]
    },
    "flavor": {
      "type": "string",
      "title": "Character flavor text",
      "maxLength": 500,
      "examples": [
        "Bloodstains on a dinner jacket? No, this is cooking sherry. How careless.",
        "Certainly madam, under normal circumstances, you may borrow the Codex Malificarium from the library vaults. However, you do not seem to be a member.",
        "It is a fine night for a stroll, wouldn't you say, Mister Morozov? Or should I say... BARON Morozov?"
      ]
    },
    "firstNight": {
      "type": "number",
      "title": "First night wake-up priority. 0 means this character doesn't wake during the first night.",
      "examples": [
        37,
        0,
        15
      ]
    },
    "firstNightReminder": {
      "type": "string",
      "title": "First night Storyteller reminder",
      "maxLength": 500,
      "examples": [
        "Show the Townsfolk character token. Point to both the *TOWNSFOLK* and *WRONG* players.",
        "Wake all Minions, allow them to choose a babysitter :reminder:",
        ""
      ]
    },
    "otherNight": {
      "type": "number",
      "title": "Other nights wake-up priority. 0 means this character doesn't wake during other nights.",
      "examples": [
        0,
        10,
        15
      ]
    },
    "otherNightReminder": {
      "type": "string",
      "title": "Other nights Storyteller reminder",
      "maxLength": 500,
      "examples": [
        "",
        "Wake all Minions, allow them to choose a babysitter :reminder: A player might die :reminder:",
        "The Fang Gu chooses a player. :reminder: If they chose an Outsider (once only): Replace the Outsider token with the spare Fang Gu token. Put the Fang Gu to sleep. Wake the target. Show the *YOU ARE* and Fang Gu tokens \u0026 give a thumbs-down. :reminder:"
      ]
    },
    "reminders": {
      "type": "array",
      "maxItems": 20,
      "default": [],
      "title": "Character reminder tokens",
      "items": {
        "type": "string",
        "maxLength": 30,
        "examples": [
          "Townsfolk",
          "Wrong",
          "Dead",
          "Is The Demon"
        ]
      }
    },
    "remindersGlobal": {
      "type": "array",
      "maxItems": 20,
      "default": [],
      "title": "Global character reminder tokens, which will be selectable even when the character is not in play.",
      "items": {
        "type": "string",
        "maxLength": 25,
        "examples": [
          "Drunk",
          "Is The Philosopher"
        ]
      }
    },
    "setup": {
      "type": "boolean",
      "title": "Whether this character has a ability that is relevant for the game setup.",
      "default": false
    },
    "jinxes": {
      "type": "array",
      "title": "Jinxes with other characters on this script",
      "items": {
        "type": "object",
        "title": "An individual Jinx pair",
        "required": [
          "id",
          "reason"
        ],
        "properties": {
          "id": {
            "type": "string",
            "title": "The ID of the other character this one is jinxed with.",
            "maxLength": 50,
            "examples": [
              "spy",
              "fanggu",
              "lilmonsta"
            ]
          },
          "reason": {
            "type": "string",
            "title": "The Jinx explanation",
            "maxLength": 500,
            "examples": [
              "If the Cannibal gains the Butler ability, the Cannibal learns this.",
              "The Mathematician learns if the Lunatic attacks a different player(s) than the real Demon attacked."
            ]
          }
        }
      }
    },
    "special": {
      "type": "array",
      "title": "Special app integration features for this character",
      "items": {
        "type": "object",
        "title": "A special app integration feature",
        "required": [
          "name",
          "type"
        ],
        "properties": {
          "type": {
            "type": "string",
            "title": "The integration type, where the feature will be used.",
            "description": "Currently supported values are:\n selection - during character selection,\n signal - during night signaling,\n ability - when clicking on the character token,\n vote - during a vote,\n reveal - at the end of the game, before characters are revealed,\n player - an ability that can be initiated by the player",
            "enum": [
              "selection",
              "ability",
              "signal",
              "vote",
              "reveal",
              "player"
            ]
          },
          "name": {
            "type": "string",
            "title": "The feature name reference",
            "description": "This is a list of the currently implemented special features and will be growing over time.",
            "enum": [
              "grimoire",
              "pointing",
              "ghost-votes",
              "distribute-roles",
              "bag-disabled",
              "bag-duplicate",
              "multiplier",
              "hidden",
              "replace-character",
              "player",
              "card",
              "open-eyes"
            ]
          },
          "value": {
            "oneOf": [
              {
                "type": "string",
                "title": "Special ability text value",
                "maxLength": 50,
                "description": "The text value that will be used by the special ability."
              },
              {
                "type": "number",
                "title": "Special ability number value",
                "description": "The numeric value that will be used by the special ability."
              }
            ]
          },
          "time": {
            "type": "string",
            "title": "At which point during the game can the ability be used",
            "enum": [
              "pregame",
              "day",
              "night",
              "firstNight",
              "firstDay",
              "otherNight",
              "otherDay"
            ]
          },
          "global": {
            "type": "string",
            "title": "Global ability scope",
            "description": "If it's a global ability that can be used without the character being in play, this property defines on which characters it can be used. This does not work on Fabled, because they are not considered to be on the Script.",
            "enum": [
              "townsfolk",
              "outsider",
              "minion",
              "demon",
              "traveller",
              "dead"
            ]
          }
        },
        "examples": [
          {
            "type": "player",
            "name": "open-eyes",
            "time": "night"
          },
          {
            "type": "signal",
            "name": "card",
            "value": "This is a Custom ST Card"
          },
          {
            "type": "ability",
            "name": "pointing",
            "time": "night",
            "global": "minion"
          },
          {
            "type": "vote",
            "name": "multiplier",
            "value": "3"
          }
        ]
      }
    }
  },
  "examples": [
    {
      "id": "washerwoman",
      "name": "Washerwoman",
      "edition": "tb",
      "team": "townsfolk",
      "firstNightReminder": "Show the Townsfolk character token. Point to both the *TOWNSFOLK* and *WRONG* players.",
      "otherNightReminder": "",
      "reminders": [
        "Townsfolk",
        "Wrong"
      ],
      "setup": false,
      "ability": "You start knowing that 1 of 2 players is a particular Townsfolk.",
      "flavor": "Bloodstains on a dinner jacket? No, this is cooking sherry. How careless.",
      "firstNight": 37,
      "otherNight": 0
    }
  ]
}

=== yoyosource/BOTC-FoF/Fabled/Glassblower/Glassblower.json
{
  "id": "glassblower",
  "edition": "custom",
  "name": "Glassblower",
  "team": "fabled",
  "firstNightReminder": "Hand out as many potions as the voting majority minus 1 divided amongst any number of players.",
  "otherNightReminder": "Hand out as many potions as the voting majority minus 1 divided amongst any number of alive players.",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Fabled/Glassblower/image.png?raw=true"
  ],
  "ability": "Each night, potions equal to the voting majority minus 1 are given out.",
  "flavor": "Sometimes, the most beautiful creations are born from shattered dreams."
}

=== yoyosource/BOTC-FoF/Townsfolk/Distiller/Distiller.json
{
  "id": "distiller",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Distiller/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Distiller/image_evil.png?raw=true"
  ],
  "name": "Distiller",
  "team": "townsfolk",
  "otherNightReminder": "Wake up the Distiller and have them choose 2 alive players. Then put them to sleep and either put a good Potion on one of the chosen players, or remove an evil potion from one of the chosen players.",
  "ability": "Each night*, choose 2 alive players; 1 receives a good potion or 1 of their evil potions break.",
  "flavor": "Ein Glas ist fabelhaft, zwei sind zu viel, und drei zu wenig."
}

=== yoyosource/BOTC-FoF/Traveller/Fugitive/Fugitive.json
{
  "id": "fugitive",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Traveller/Fugitive/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Traveller/Fugitive/image_good.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Traveller/Fugitive/image_evil.png?raw=true"
  ],
  "name": "Fugitive",
  "team": "traveller",
  "otherNightReminder": "Wake up a living player and have them choose either 1 or 2, then put them to sleep.\nWake up another living player and have them choose 1 or 2, then put them to sleep.\n  If at least 1 of them choose 1, put a Good Potion on the other player.\n  If only 1 of them chose 2, wake them and show them the other player and their potions.\n  If both players chose 2, put an evil potion on both.",
  "ability": "Each night* 2 players choose either 1) The other receives a Good potion, or 2) to learn the other and their potions. If both choose 2, each receive an Evil potion instead.",
  "flavor": "I've run so far away,\nI ran all night and day,\nso far away,\nbut I couldn't get away.",
  "special": [
    {
      "type": "signal",
      "name": "card",
      "value": "makes you an offer. Pick 1 or 2.",
      "time": "night"
    },
    {
      "type": "signal",
      "name": "card",
      "value": "makes you an offer. Pick 1 or 2.",
      "time": "night",
      "global": "outsider"
    },
    {
      "type": "signal",
      "name": "card",
      "value": "makes you an offer. Pick 1 or 2.",
      "time": "night",
      "global": "minion"
    },
    {
      "type": "signal",
      "name": "card",
      "value": "makes you an offer. Pick 1 or 2.",
      "time": "night",
      "global": "demon"
    },
    {
      "type": "signal",
      "name": "card",
      "value": "makes you an offer. Pick 1 or 2.",
      "time": "night",
      "global": "traveller"
    }
  ]
}

=== yoyosource/BOTC-FoF/Townsfolk/Diviner/Diviner.json
{
  "id": "diviner",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Diviner/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Diviner/image_evil.png?raw=true"
  ],
  "reminders": [
    "Used"
  ],
  "name": "Diviner",
  "team": "townsfolk",
  "firstNightReminder": "Choose a player to receive a Potion.",
  "otherNightReminder": "Choose a player to receive a Potion.",
  "ability": "Each night, a player receives a potion. Once per game at night, when a player would die, their potions break instead.",
  "flavor": "People were doubtful about their abilities. The tone quickly changed when they were banned from every local gambling hall."
}

=== yoyosource/BOTC-FoF/Townsfolk/Chandler/Chandler.json
{
  "id": "chandler",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Chandler/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/Chandler/image_evil.png?raw=true"
  ],
  "reminders": [
    "Correct"
  ],
  "name": "Chandler",
  "team": "townsfolk",
  "otherNightReminder": "If the *Correct* reminder is on the Chandler they can only receive the selected Potion. Put one of the selected Potions on them.",
  "ability": "Each day, visit the Storyteller & name a potion; learn an open statement; solve it & tonight receive, and only receive, that potion.",
  "flavor": "Oh bright light,\ngrant me sight,\nfor what might,\nbe just right,\ntonight.\n-Sign outside the Chandler's shop"
}

=== yoyosource/BOTC-FoF/Traveller/Socialist/Socialist.json
{
  "id": "socialist",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Traveller/Socialist/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Traveller/Socialist/image_good.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Traveller/Socialist/image_evil.png?raw=true"
  ],
  "name": "Socialist",
  "team": "traveller",
  "ability": "Up to three times each night when a player receives a potion (not from the Socialist); another player receives a potion of the opposite alignment.",
  "flavor": "The workers must seize the means of production!"
}

=== yoyosource/BOTC-FoF/Townsfolk/TollInspector/TollInspector.json
{
  "id": "tollinspector",
  "edition": "custom",
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/TollInspector/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Townsfolk/TollInspector/image_evil.png?raw=true"
  ],
  "name": "Toll Inspector",
  "team": "townsfolk",
  "otherNightReminder": "Wake up the Toll Inspector and show them the cauldron.",
  "ability": "Each night*, eye the cauldron.",
  "flavor": "I had to pay a ransom of six hundred pounds in gold. All might have gone well even yet, only that, by ins and outs and crookedness of laws, I was shorn like a sheep that is clipped to the quick."
}

=== yoyosource/BOTC-FoF/Minion/Thug/Thug.json
{
  "id": "thug",
  "edition": "custom",
  "reminders": [
    "Mad"
  ],
  "image": [
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Minion/Thug/image.png?raw=true",
    "https://github.com/yoyosource/BOTC-FoF/blob/master/Minion/Thug/image_good.png?raw=true"
  ],
  "name": "Thug",
  "team": "minion",
  "firstNightReminder": "Wake up the Thug and have them choose a player and a character. Put the Thug's *Mad* reminder token on that player. Put the Thug to sleep and wake up the chosen player. Inform them that they were chosen by the Thug and the character chosen by the Thug.",
  "otherNightReminder": "Wake up the Thug and have them choose a player and a character. Put the Thug's *Mad* reminder token on that player. Put the Thug to sleep and wake up the chosen player. Inform them that they were chosen by the Thug and the character chosen by the Thug.",
  "ability": "Each night, choose a player and a character; tomorrow they are \"mad\" that that character is NOT in play or 2 players might receive an evil potion.",
  "flavor": "You're humming, Sam. That means that something awful is going to happen to somebody."
}
